import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/Providers";
import { Navbar } from "@/components/navbar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PocketBase Datos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const pbAuthCookie = cookieStore.get('pb_auth');
  const pbAdminAuthCookie = cookieStore.get('pb_admin_auth');
  const isLoggedIn = pbAuthCookie || pbAdminAuthCookie;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {isLoggedIn && <Navbar />}
          {children}
          <Toaster />
        </Providers>
        <Script src="http://localhost:3030/component-selector.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}